# Generated by Django 4.0.2 on 2022-02-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/avatar_hy6hxz.jpg', null=True, upload_to='images'),
        ),
    ]
